### ISSUE TITLE
DogeHouse.py bot low uptime

### ISSUE THREAD

**Issue by asxlvm** [Arthurdw/dogehouse.py#11]
Hey! Today I checked UptimeRobot to see stats on the Uptime of my Discord bots and my Dogehouse bot, I saw that the Dogehouse bot had a big difference in uptime
![IMG_20210330_111126](https://user-images.githubusercontent.com/81298611/112964723-e0325580-9148-11eb-859e-34750b4f8a8d.jpg)

Does that have something to do with the loop (that it's set to 30 minutes or smth) or is it just the socket disconnecting because it's not receiving anything?

**Comment by Arthurdw** [comment]
No, the dogehouse.py implements the WebSocket heartbeat. So this should not happen.

From how much time is this taken? (Because I'm unable to reproduce this)

**Comment by asxlvm** [comment]
Okay sorry, also my error, for some reason my web server wasn't getting offline so the repl killed itself after 30 minutes, everything great now :)
