### ISSUE TITLE
BaseUser doesn't trigger if the argument ends with a whitespace

### ISSUE THREAD

**Issue by asxlvm** [Arthurdw/dogehouse.py#14]
So, DogeHouse doesn't remove white spaces when a message has been sent with a space at the end, ex.;
`d!fight @asylum ` , it wouldn't trigger because of the whitespace, so you'd have to remove the whitespace at the end for it to work.

I use BaseUser as my user arg. and I'm not sure if this happens with any other arg or if there's a way to fix that straight in your library or do I have to make an if endswith check in my code?

**Comment by Arthurdw** [comment]
I'll look into that on Monday. Thanks for reporting. ^^

**Comment by Arthurdw** [comment]
This issue has been resolved in [1.3.2](https://github.com/Arthurdw/dogehouse.py/releases/tag/1.3.2).

Thanks for reporting this issue. ^^
