### ISSUE TITLE
Fatal bug in new version

### ISSUE THREAD

**Issue by asxlvm** [Arthurdw/dogehouse.py#16]
![IMG_20210404_213704](https://user-images.githubusercontent.com/81298611/113519671-fc415700-958d-11eb-85e6-c0d8aa8b081b.jpg)

This happened when I started the bot after updating to 1.4.

**Comment by Arthurdw** [comment]
Ooh, I already know why. Sorry, let me resolve this.

**Comment by Arthurdw** [comment]
This issue has been resolved in `1.5.0`.

Feel free to check out [the example](https://github.com/Arthurdw/dogehouse.py/blob/main/examples/telemetry.py) on how to work with telemetry now.

Thanks for reporting this issue!

(for telemetry you'll have to install it using `pip install -U dogehouse[telemetry]`)
