### ISSUE TITLE
on_permissions_change event

### ISSUE THREAD

**Issue by asxlvm** [Arthurdw/dogehouse.py#18]
Hey, I'm not sure if we have an `on__permissions_change` event so we can detect when someone's permissions (admin, mod) have been changed

**Comment by Arthurdw** [comment]
This feature has been implemented in v[2.0.0](https://github.com/Arthurdw/dogehouse.py/releases/tag/2.0.0).

Docs: [on_permission_change](https://dogehouse.arthurdw.com/#/api?id=on_permission_change)

Thanks for your suggestion!
