### ISSUE TITLE
You cannot retrieve is_mod from BaseUser and User object

### ISSUE THREAD

**Issue by asxlvm** [Arthurdw/dogehouse.py#20]
**Describe the bug**
You cannot get `is_mod` from the User / BaseUser object, look at screenshots.

**To Reproduce**
Try getting `is_mod` from User or BaseUser object, it returns an attribute error

And/or code:
```py
	@command
	async def altcheck(self, ctx: Context):
		authormsg = ctx.author
		#authormsg = await self.convertuser(ctx.author.id)
		if authormsg.is_mod or authormsg.is_admin == True:
			pass
		else:
			return await self.send("You don't have permission to do that.", whisper=[ctx.author.id])
		await self.send("This may take a while, be patient.", whisper=[ctx.author.id])
		users = []
		for user in self.room.users:
			userdata = await self.returnavinfo(user)
			if userdata == "Twitter":
				continue
			else:
				users.append(userdata)
		
		userssend = "".join(users)
		await self.send(userssend, whisper=[ctx.author.id])


```

**Expected behavior**
It should return a boolean for `is_mod`.

**Screenshots**
![IMG_20210409_203755](https://user-images.githubusercontent.com/81298611/114226420-d5ab6380-9973-11eb-94c5-d1799bfe1278.jpg)
![IMG_20210409_203703](https://user-images.githubusercontent.com/81298611/114226442-db08ae00-9973-11eb-81fc-6a9650f7f892.jpg)

**Desktop (please complete the following information):**
 - OS: [Android 10]
 - Browser [Brave]
 - Version [1.22.71]

**Additional context**
My DogeHouse.py version is 1.5.1

**Comment by Arthurdw** [comment]
As stated in [dogehouse.entities.User](https://dogehouse.arthurdw.com/#/api?id=entity-user), you can get the permissions of a using by accessing the `room_permissions` property.
