### ISSUE TITLE
I cant import it to my project

### ISSUE THREAD

**Issue by Stroooooo** [Arthurdw/dogehouse.py#21]
idk why

**Comment by Arthurdw** [comment]
Can you show the error?

**Comment by asxlvm** [comment]
@StruanMclean Make sure it's installed, to install it, type `pip install dogehouse`
If you're running it in replit, get in the "Packages" tab and find it there

**Comment by Arthurdw** [comment]
@StruanMclean can you let us know when you have resolved this? Or if you don't know why, can you send us the full error?

**Comment by Stroooooo** [comment]
> @StruanMclean can you let us know when you have resolved this? Or if you don't know why, can you send us the full error?

ok I will show the error =)

tomorrow because its late in scotland

**Comment by Arthurdw** [comment]
Any updates on this? *(For the logs)*

**Comment by Stroooooo** [comment]
hello here is a picture of the issue 

https://ibb.co/Ntw0Vhs
https://ibb.co/s1F3tXc

idk if it was just how I imported it or if its a package issue.

hope this helps =)

**Comment by Arthurdw** [comment]
The package was installed on a different python version.
