### ISSUE TITLE
We now can get fetch_user

### ISSUE THREAD

**Issue by asxlvm** [Arthurdw/dogehouse.py#22]
**Is your feature request related to a problem? Please describe.**
n o

**Describe the solution you'd like**
We can now probably get a fetch_user feature because it is possible in the client, ex. in screenshot

**Describe alternatives you've considered**
I haven't considered any because there's only one way

**Additional context**
![Screenshot_2021-04-17-18-22-46-587_com brave browser](https://user-images.githubusercontent.com/81298611/115120639-d3b65580-9fae-11eb-9804-4b70e6e1601a.jpg)

**Comment by Arthurdw** [comment]
This has already been put on the todo list. (See #4 *([comment](https://github.com/Arthurdw/dogehouse.py/issues/4#issuecomment-810097875))*)
