### ISSUE TITLE
TypeError: object of type 'bool' has no len()

### ISSUE THREAD

**Issue by saihnii4** [Arthurdw/dogehouse.py#23]
**Describe the bug**
When receiving a User's permissions, the `represents` function doesn't cast non-string objects to a string, instead, it casts string objects to a string, meaning the object will always be a non-string, causing an error.

**To Reproduce**
1. Make a simple dogehouse bot
2. Call `__repr__` on User.room_permissions
3. See error

And/or code:
```py
from dogehouse import DogeClient, event, command
from dogehouse.entities import User

class Client(DogeClient):
    @event
    async def on_ready(self):
        pass

    @command
    async def test(self, ctx):
        user = await self.fetch_user(ctx.author.id)
        print(user.room_permissions.__repr__()) # You can exclude the __repr__ if you want
```

**Expected behavior**
A string printed in stdout, something along the lines of `<Permission asked_to_speak='False' is_mod='False' is_admin='True' is_speaker='False'>`

**Screenshots**
![Screenshot from 2021-04-18 11-51-21](https://user-images.githubusercontent.com/81787757/115133659-82ed3e00-a03c-11eb-84a2-f5668b6872e9.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux x86_64
 - Browser: Firefox
 - Version: 5.9.16-1-MANJARO

**Additional context**
You can solve this issue by swapping `item` and `f"'{item}'"` in line 52 of the /represents/representation.py file

**Comment by Arthurdw** [comment]
The issue has been resolved in [represents v0.1.1](https://pypi.org/project/represents/).
Please update the represents module by executing the following command:
```bash
# Unix based OS:
$ python3 -m pip install -U represents
# Windows:
$ py -3 -m pip install -U represents
```
