### ISSUE TITLE
NotEnoughArguments exception not called

### ISSUE THREAD

**Issue by asxlvm** [Arthurdw/dogehouse.py#24]
**Describe the bug**
The NotEnoughArguments error doesn't get called

**To Reproduce**
1. Try the command and event below without any arguments:
2. The output is `tuple index out of range` instead of NotEnoughArguments

**Expected behavior**
The error should return NotEnoughArguments instead of tuple index out of range

**Code**
```py
	@event
	async def on_error(self, error):
		print(error)
		if isinstance(error, dogehouse.exceptions.CommandNotFound):
			print("not found")
		elif isinstance(error, dogehouse.exceptions.NotEnoughArguments):
			print("yisiso")
		else:
			print("no")

	@command
	async def testerror(self, ctx: Context, tellemes):
		await self.send(tellemes)
```

**Screenshots**
![IMG_20210420_102559](https://user-images.githubusercontent.com/81298611/115363548-da1d1b00-a1c2-11eb-9500-cf01de2c0368.jpg)

**Desktop (please complete the following information):**
 - OS: [linux]
 - Browser [replit ide bruh?]
 - Version [the newest i guess]
 -  Is this stuff really needed? I don't think OS and browser matter really

**Additional context**
no

**Comment by Arthurdw** [comment]
This issue has been resolved in v`2.1.3`
