### ISSUE TITLE
Things we need;

### ISSUE THREAD

**Issue by asxlvm** [Arthurdw/dogehouse.py#4]
So, I'm new to Github and I don't know where to type comments so I'll issue it.
The things we need the most;
1. A documentation for the module! I had to look through the source code to find what I need
2. Functions that can do these things: "Make Mod", "Make Room Admin", "Ban from Chat", "Ban from Room"

**Comment by Arthurdw** [comment]
Yeah, I'll implement those later. Documentation will also be added later.

**Comment by asxlvm** [comment]
Okay! Though thank you so much for making this module, you made everything easier <3

**Comment by Arthurdw** [comment]
Features:
- [x] Ask to speak
- [x] Make mod
- [x] Make room admin
- [x] Ban from room
- [x] Ban from room chat
- [x] Remove message
- [x] Umod
- [x] Unban
- [x] Go back to listener
- [x] Set other user to listener
- [x] Add speaker
- [x] On speaker removed
- [x] On chat user banned
- [x] On message deleted
- [x] On speaker request

I'll be trying to implement these first.

**Comment by asxlvm** [comment]
The checkmarked features are already done or the ones you're working at?

**Comment by Arthurdw** [comment]
> The checkmarked features are already done or the ones you're working at?

The one's done, I just pushed them to the repo.
They aren't included yet, I'll create a new release when I've added the last 3 event listeners.

Tomorrow I'll look into Sphinx documentation or smth.

**Comment by asxlvm** [comment]
Okayy, but good job on this stuff, you're doing great!

**Comment by Arthurdw** [comment]
I released the new package with those features.

**Comment by asxlvm** [comment]
Hey! Don't wanna be annoying but, do we have a **wait_for** event? Would really help having it!

**Comment by Arthurdw** [comment]
I'll add it to the todo list.

**Comment by Arthurdw** [comment]
I implemented the `wait_for` event.

**Comment by asxlvm** [comment]
We need a way to make easy-to-do cooldowns for commands, and also, is there a `isMod?` and `isAdmin?` check?

**Comment by Arthurdw** [comment]
Great idea's. I'be added these to the todo-list. I'm going to learn how I can create convertors in python first tho.

**Comment by Arthurdw** [comment]
Commands, command aliases & command cooldowns have been implemented.
The `is_mod` & `is_admin` attributes can be found in the `User` object its `room_permissions` parameter. (Which is a `Permissions` object)

**Comment by asxlvm** [comment]
We need a **fetch_user** function (if it's possible with the API) so we can get usernames form the user ID :D

**Comment by Arthurdw** [comment]
Yeah, that was in the planning, that function is already in place in `1.3.0` but it hasn't implemented the API fetch yet. (Now it looks through the cache to find a user.)

**Comment by Arthurdw** [comment]
After a lot of time, we are finally able to close this issue.

You are now able to fetch a user. See [the example](https://github.com/Arthurdw/dogehouse.py/blob/main/examples/user_fetch.py)
