### ISSUE TITLE
Default values don't work

### ISSUE THREAD

**Issue by asxlvm** [Arthurdw/dogehouse.py#8]
![IMG_20210326_172512](https://user-images.githubusercontent.com/81298611/112669479-0eb9e300-8e60-11eb-964f-0c4efcb64c34.jpg)

![IMG_20210326_172445](https://user-images.githubusercontent.com/81298611/112669450-06fa3e80-8e60-11eb-85ab-87dd96cdd7a7.jpg)

This is the code that I'm using;
```py
  @command
  async def pp(self, ctx: Message, *, user: User = None):
    print(user)
    if user == None:
      user2 = ctx.author.mention
      print(user)
    else:
      user2 = user.mention
    pps = [ I don't wanna make the code long so I'm not including the list ]
    
    pprnd = random.choice(pps)
      
    await self.send(f"{user2}'s pp: ㅤㅤㅤ{pprnd}")
```
Before the update, the tagging worked but obviously the ctx.author didn't, now it's vice-versa.

**Comment by Arthurdw** [comment]
You are using `user.mention` when a value has been provided. This is because you are trying to convert the user using a converter in the method definition. Convertors are currently not implemented, but are planned for the future.

**Comment by asxlvm** [comment]
Okay, then how would I use the correct code?

**Comment by Arthurdw** [comment]
It would probably be something like this:
```py
from typing import Union
from random import randint
from dogehouse import DogeClient, event, command
from dogehouse.entities import User, UserPreview, Message


class Client(DogeClient):
    @event
    async def on_ready(self):
        print(f"Successfully connected as {self.user}!")
        await self.create_room("Hello World")
        
    @command
    async def pp(self, ctx: Message, *, user: str = None):
        if user and user.startswith('@'):
            user = user[1::]
        try:
            user: Union[User, UserPreview] = ctx.author if user is None else \
                [usr for usr in self.room.users if \
                    str(usr) == user or (isinstance(usr, User) and usr.displayname == user)][0]
        except IndexError:
            return await self.send(f"User '{user}' not found!")    
        await self.send(f"{user.mention if isinstance(user, User) else user.displayname} 's pp: 8{randint(1, 8) * '='}>")

if __name__ == "__main__":
    Client("token", "refresh_token").run()
```

(Little note, the example script will recognize everyone from in the room (by using a mention or username), but because of the structure of the wrapper, not the bot client itself. For the bot client itself it will only detect the display name as that is a `UserPreview` object. [You could bypass this by adding some extra checks])

**Comment by asxlvm** [comment]
![IMG_20210327_131856](https://user-images.githubusercontent.com/81298611/112720507-21372980-8eff-11eb-98dc-6435e3aaa399.jpg)

I'm not sure what I'm doing wrong then

```py
  @command
  async def testuser(self, ctx: Message, *, user: str = None):
    if user and user.startswith('@'):
      user = user[1::]
    try:
      user: Union[User, UserPreview] = ctx.author if user is None else \
        [usr for usr in self.room.users if \
          str(usr) == user or (isinstance(usr, User) and usr.displayname == user)][0]
    except IndexError:
      return await self.send(f"User '{user}' not found!")
      
    await self.send(f"{user.displayname} • ID: {user.id}")
```

**Comment by Arthurdw** [comment]
I'm unable to reproduce this.
![image](https://user-images.githubusercontent.com/38541241/112733360-f4efcd00-8f3f-11eb-8d6c-5ca8960aefad.png)
